wsgi/openshift/django/conf/project_template/project_name/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', '{{ project_name }}.views.home', name='home'),
    # url(r'^{{ project_name }}/', include('{{ project_name }}.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

wsgi/openshift/la_habilleur/urls.py
from django.conf.urls.defaults import patterns, url
from la_habilleur import views

urlpatterns = patterns('',
    url(r'^$', views.display_wardrobe, name='display-wardrobe'),
    url(r'^enter-suit/', views.enter_suit, name = 'enter-suit'),
    url(r'^view-suit-rank/', views.view_suit_rank, name = 'view-suit-rank'),
    url(r'^add-to-wardrobe/', views.add_to_wardrobe, name='add-to-wardrobe'),
    url(r'^drop-wardrobe/', views.drop_wardrobe, name='drop-wardrobe')
)

wsgi/openshift/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^la_habilleur/', include('la_habilleur.urls',
                                   namespace='la_habilleur')),
    url(r'^admin/', include(admin.site.urls)),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
)

wsgi/openshift/la_habilleur/models.py
from django.db import models
from picklefield.fields import PickledObjectField


class Wardrobe(models.Model):
    username = models.CharField(max_length = 100)
    wardrobe = PickledObjectField()

    def __unicode__(self):
        return self.username

    def best_suits(self):
        return None

    def add_cloth(self):
        return None

    def fill_the_suit(self):
        return None

wsgi/openshift/la_habilleur/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseBadRequest
from django.shortcuts import get_object_or_404, render
import core
from la_habilleur.models import Wardrobe
from django.utils.datastructures import MultiValueDictKeyError

def index(request):
    return HttpResponse("Hello")

def display_wardrobe(request):
    the_wardrobe = get_object_or_404(Wardrobe, pk=1)
    return render(request, 'la_habilleur/add_cloth.html', {
        'the_wardrobe': the_wardrobe.wardrobe,
        'cloth_db':  core.cloth_db.ClothDB().clothes_by_slot})

def add_to_wardrobe(request):
    the_wardrobe = get_object_or_404(Wardrobe, pk=1)
    try:
        id_to_add = core.cloth_db.ClothDB().get_by_name(
            request.POST['cloth_name']).id
    except (ValueError, MultiValueDictKeyError, KeyError):
        return render(request, 'la_habilleur/add_cloth.html', {
         'the_wardrobe': the_wardrobe.wardrobe,
            'cloth_db': core.cloth_db.ClothDB().clothes_by_slot,
            "error_message": "Invalid item"})

    cloth_to_add = core.cloth_db.Cloth(id_to_add, (0, 0, 0))
    if cloth_to_add in the_wardrobe.wardrobe:
        return render(request, 'la_habilleur/add_cloth.html', {
            'the_wardrobe': the_wardrobe.wardrobe,
            'cloth_db': core.cloth_db.ClothDB().clothes_by_slot,
            "error_message": "Duplicate entry"})
    the_wardrobe.wardrobe.append(cloth_to_add)
    the_wardrobe.save()
    return HttpResponseRedirect(reverse('la_habilleur:display-wardrobe'))

def drop_wardrobe(request):
    the_wardrobe = get_object_or_404(Wardrobe, pk=1)
    the_wardrobe.wardrobe = []
    the_wardrobe.save()
    return HttpResponseRedirect(reverse('la_habilleur:display-wardrobe'))

def enter_suit(request):
    return render(request, 'la_habilleur/calc_suit_rank.html', {})

def view_suit_rank(request):
    cloth_ids = request.POST['suit']
    cloth_ids = cloth_ids.split()
    cloth_ids = map(int, cloth_ids)
    ranker = core.pair_ranker.RankerPairSimple()
    rank = ranker.rank_items(cloth_ids)
    return HttpResponse(rank)

wsgi/openshift/la_habilleur/templates/la_habilleur/add_cloth.html
<!DOCTYPE html>
<html>
<head>
<link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet">
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}
<link href="{{ STATIC_PREFIX }}css/bootstrap-tree.css" rel="stylesheet">

</head>
<body>
  <div class="navbar navbar-static-top">
    <div class="navbar-inner">
      <div class="container">
        <ul class='nav'>
          <li>
            <a class="brand" href="/la_habilleur/">L'habilleur Intelligente</a>
          </li>
          <li>
            <ul class="breadcrumb">
              <li><a href = "/la_habilleur/">Manage wardrobe</a><span class="divider">/</span></li>
    	    </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="container">
    {% if error_message %}
    <div class="row">
      <div class="span12">
	<div class="alert alert-error">
	  <p><strong>{{ error_message }}</strong></p>
	</div>
      </div>
    </div>
    {% endif %}
    <div class="row">
      <div class="span3">
	{% load url from future %}
	<a href="{% url 'la_habilleur:drop-wardrobe' %}">Drop wardrobe</a>
	<h4>Current wardrobe</h4>
	{{ the_wardrobe }}
      </div>
      <div class="span9">
	<div class="span3">
	  <div class="well">
            <ul class="tree">
	      {% load la_habileur_template %}
	      {% for slot in cloth_db.iterkeys %}
              <li>
                <a href="#" role="branch" class="tree-toggle closed" data-toggle="branch"
		   data-value="Bootstrap_Tree">Slot {{ slot }}</a>
                <ul class="branch closed">
		  {% for cloth in cloth_db|lookup:slot %}
                  <li><a href="#" role="leaf" id="nut"
			 onclick="UpdateSelection('{{ cloth.name }}')">{{ cloth.name }}</a></li>
		  {% endfor %}
                </ul>
              </li>
	      {% endfor %}
            </ul>
          </div><!--/.well -->

	</div>
	<h4>Add item</h4>
	<form action="{% url 'la_habilleur:add-to-wardrobe' %}" method="post" class="form-inline">
	  {% csrf_token %}
	  <input type="text" name="cloth_name" id="cloth_to_add" autocomplete="off"
		 data-provide="typeahead"
		 data-items="4" data-source='[{% for cloth_list in cloth_db.itervalues %}
		 {% for cloth in cloth_list %} "{{ cloth.name }}"
		 {% if not forloop.parentloop.last or not forloop.last %},{% endif %}
		 {% endfor %}
		 {% endfor %}
		 ]'>
	  <button type="submit" class="btn">Add</button>
	</form>
      </div>
    </div>
  </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.js"></script>
  <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
  <script src="{{ STATIC_PREFIX }}js/bootstrap-tree.js"></script>
  <script src="{{ STATIC_PREFIX }}la_habilleur/js/display_wardrobe.js"></script>
</body>
</html>

wsgi/openshift/la_habilleur/templates/la_habilleur/calc_suit_rank.html
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
{% load url from future %}
<form action="{% url 'la_habilleur:view-suit-rank' %}" method="post">
{% csrf_token %}
    <input type="text" name="suit" id="suit" />
<input type="submit" value="Calc" />
</form>